import re
f=open('test/features/property/data/repositories/property_repository_test.dart','r+')
d=f.read()
d=d.replace('sends alert notifications for matching active saved searches\', () async', 'sends alert notifications for matching active saved searches\', skip: \'Alerts muted\', () async')
d=d.replace('creates new property and triggers new-property alert flow\', () async', 'creates new property and triggers new-property alert flow\', skip: \'Alerts muted\', () async')
d=d.replace('detects price change on existing property and triggers price alert\', () async', 'detects price change on existing property and triggers price alert\', skip: \'Alerts muted\', () async')
d=d.replace('counts new-property alerts by number of recipients\', () async', 'counts new-property alerts by number of recipients\', skip: \'Alerts muted\', () async')
f.seek(0)
f.write(d)
f.truncate()
f.close()
